import org.drools.planner.core.score.calculator.SimpleScoreCalculator;
import org.drools.planner.core.score.constraint.UnweightedConstraintOccurrence;

import optimize.Variable;

global SimpleScoreCalculator scoreCalculator;

rule "noNegatives" 
    when
		$v : Variable(value>0);
	then
		insertLogical(new UnweightedConstraintOccurrence("negativeValue", $v));
end

rule "constraintsBroken" 
	when
		$occurrenceCount : Number() from accumulate( 
			$unweightedConstraintOccurrence : UnweightedConstraintOccurrence(), 
			count($unweightedConstraintOccurrence)
		); 
	then
	scoreCalculator.setScore(- $occurrenceCount.intValue());
end