package spacesim

import spacesim.Ship

rule "Start Moving"
	no-loop
	when
		s:Ship(forwardThrust==false, enemyShip!=null)
	then 
		s.forwardThrust=true;
		s.angle=s.ea;
		update(s);
end

rule "Sling Shot Fire"
	when
		s:Ship((ed<600 && ed<200), fireMissile==false)
	then
		s.fireMissile=true;
		update(s);
end

rule "Fire"
	when
		s:Ship(ed<100, fireMissile==false)
	then
		s.fireMissile=true;
		update(s);
end
/*
rule "Evasive Maneuvers"
	no-loop
	when
		s:Ship(enemyMissile.alive==true)
	then
		s.angle=s.ema-180;
		update(s);
end
*/

rule "You have won or draw"
	no-loop
	when
		s:Ship(enemyMissile.alive==false, enemyShip.alive==false, 
			eval(Math.abs(dx)>=0.01||Math.abs(dy)>=0.01))
	then
		s.angle=Util.angle(0, 0, s.dx, s.dy)-181;
		update(s);
end