package spacesim

import spacesim.Missile

rule "Detonate"
	when
		m:Missile(eval(ed<explosionRadius-2), boom==false)
	then 
		m.boom=true;
		update(m);
end

rule "Follow By Aiming Straight At Target"
	no-loop
	when
		m:Missile(angle!=ea, enemyMissile.alive==false)
	then
		m.angle=m.ea;
		update(m);
end

rule "Slowdown before target"
no-loop
when
	m:Missile(ed == 200)
then
	m.angle=m.ea+10;
	update(m);
end
//boom==false
/*
rule "Shoot Down Other Missile"
	no-loop
	when
		m:Missile(boom==false, enemyMissile.alive==true)
	then
		m.angle=m.ema;
		update(m);
	end
*/
rule "Shoot Down Other Ship"
	no-loop
	when
		m:Missile(boom==false)
	then
		m.angle=m.ea;
		update(m);
	end