package spacesim

import spacesim.Ship

rule "Start Moving"
	no-loop
	when
		s:Ship(forwardThrust==false, enemyShip!=null)
	then 
		s.forwardThrust=true;
		s.angle=s.ea-25;
		update(s);
end

rule "You May Fire When Ready Grimley"
	when
		s:Ship(ed<100, fireMissile==false)
	then
		s.fireMissile=true;
		update(s);
end

rule "Avoid Missiles"
	no-loop
	when
		s:Ship(enemyMissile.alive==true)
	then
		s.angle=s.ema-180;
		update(s);
end

rule "Brake For Victory"
	no-loop
	when
		s:Ship(enemyMissile.alive==false, enemyShip.alive==false, 
			eval(Math.abs(dx)>=0.01||Math.abs(dy)>=0.01))
	then
		s.angle=Util.angle(0, 0, s.dx, s.dy)-180;
		update(s);
end