package spacesim

import spacesim.Missile
import spacesim.Util

rule "Detonate"
	when
		//we want fuel to be less than 900 so we don't blow ourselves up
		m:Missile(ed<explosionRadius, boom==false, fuel<900)
	then 
		m.boom=true;
		update(m);
end

rule "Follow To Ship's Future Path"
	no-loop
	when
		m:Missile(boom==false)
	then
		//calculate where the ship will be and aim at that
		m.angle=Util.angle(m.x, m.y, (m.enemyShip.dx-m.dx)*1.4*m.ed+m.enemyShip.x, 
			(m.enemyShip.dy-m.dy)*1.4*m.ed+m.enemyShip.y);
		update(m);
end